/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otomataproje;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author MONSTER
 */
public class OtomataMain extends javax.swing.JFrame {

    /**
     * Creates new form OtomataMain
     */
    public OtomataMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        yazi_alani = new javax.swing.JTextArea();
        nfa_olustur_buton = new javax.swing.JButton();
        dfa_olustur_buton = new javax.swing.JButton();
        cizimin_yapilacagi_alan = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Mdosya_buton = new javax.swing.JMenu();
        dosyaAc_buton = new javax.swing.JMenuItem();
        dosyaKaydet_buton = new javax.swing.JMenuItem();
        cikis_buton = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        ornekBir_buton = new javax.swing.JMenuItem();
        ornekiki_buton = new javax.swing.JMenuItem();
        ornekUc_buton = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        yardim_buton = new javax.swing.JMenuItem();
        hakkimizda_buton = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        yaziTipi_buton = new javax.swing.JMenuItem();
        yaziRengi_buton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Otomata Projesi");

        yazi_alani.setColumns(20);
        yazi_alani.setRows(5);
        jScrollPane1.setViewportView(yazi_alani);

        nfa_olustur_buton.setText("NFA OLUŞTUR");

        dfa_olustur_buton.setText("DFA OLUŞTUR");

        cizimin_yapilacagi_alan.setText("ÇİZİM YAPILACAK ALAN");

        Mdosya_buton.setText("Dosya");

        dosyaAc_buton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        dosyaAc_buton.setText("Dosya Aç");
        dosyaAc_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyaAc_butonActionPerformed(evt);
            }
        });
        Mdosya_buton.add(dosyaAc_buton);

        dosyaKaydet_buton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        dosyaKaydet_buton.setText("Dosya Kaydet");
        dosyaKaydet_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyaKaydet_butonActionPerformed(evt);
            }
        });
        Mdosya_buton.add(dosyaKaydet_buton);

        cikis_buton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        cikis_buton.setText("Çıkış");
        cikis_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikis_butonActionPerformed(evt);
            }
        });
        Mdosya_buton.add(cikis_buton);

        jMenuBar1.add(Mdosya_buton);

        jMenu5.setText("Örnekler");

        ornekBir_buton.setText("Örnek 1");
        ornekBir_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ornekBir_butonActionPerformed(evt);
            }
        });
        jMenu5.add(ornekBir_buton);

        ornekiki_buton.setText("Örnek 2");
        ornekiki_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ornekiki_butonActionPerformed(evt);
            }
        });
        jMenu5.add(ornekiki_buton);

        ornekUc_buton.setText("Örnek 3");
        ornekUc_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ornekUc_butonActionPerformed(evt);
            }
        });
        jMenu5.add(ornekUc_buton);

        jMenuBar1.add(jMenu5);

        jMenu4.setText("Yardım");

        yardim_buton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        yardim_buton.setText("Yardım");
        yardim_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yardim_butonActionPerformed(evt);
            }
        });
        jMenu4.add(yardim_buton);

        hakkimizda_buton.setText("Hakkımızda");
        hakkimizda_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hakkimizda_butonActionPerformed(evt);
            }
        });
        jMenu4.add(hakkimizda_buton);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Ayarlar");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        yaziTipi_buton.setText("Yazı Tipi");
        yaziTipi_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaziTipi_butonActionPerformed(evt);
            }
        });
        jMenu1.add(yaziTipi_buton);

        yaziRengi_buton.setText("Yazı Rengi");
        yaziRengi_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaziRengi_butonActionPerformed(evt);
            }
        });
        jMenu1.add(yaziRengi_buton);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cizimin_yapilacagi_alan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(nfa_olustur_buton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(dfa_olustur_buton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 892, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nfa_olustur_buton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(dfa_olustur_buton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(cizimin_yapilacagi_alan, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dosyaAc_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyaAc_butonActionPerformed
        JFileChooser fc = new JFileChooser();
        int i = fc.showOpenDialog(this);     
        if(i == JFileChooser.APPROVE_OPTION){           
            File file = fc.getSelectedFile();
            String icerik = "";
            
            try(Scanner scanner = new Scanner(new BufferedReader(new FileReader(file)))){
                
                while(scanner.hasNextLine()){
                    
                    icerik += scanner.nextLine() + "\n";
                    
                }
                yazi_alani.setText(icerik);
                
            } catch (FileNotFoundException ex) {    //Dosya Bulunamadı Hatası!
                Logger.getLogger(OtomataMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_dosyaAc_butonActionPerformed

    private void dosyaKaydet_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyaKaydet_butonActionPerformed
        JFileChooser fc = new JFileChooser();
        int cevap = fc.showSaveDialog(this);
        
        if(cevap == JFileChooser.APPROVE_OPTION){
            
            String dosya_yolu = fc.getSelectedFile().getPath(); //Seçilen dosyanın "dosya yolunu alma" işlemi yapılmakta. getPath() = dosya yolu
        
            try(FileWriter writer = new FileWriter(dosya_yolu)){
                
                writer.write(yazi_alani.getText());
                
                
            } catch (IOException ex) {
                Logger.getLogger(OtomataMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
    }//GEN-LAST:event_dosyaKaydet_butonActionPerformed

    private void cikis_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikis_butonActionPerformed
        System.exit(0);            
    }//GEN-LAST:event_cikis_butonActionPerformed

    private void yardim_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yardim_butonActionPerformed
        JOptionPane.showMessageDialog(this, "Harflerle Düğüm Kümeleri Belirlenir；\n" +
                    "(0,1,$),(a,b,$) ile gidilecek durumlar belirlenir örnek bir girdi Aşağıdaki gibidir\n" +
                    "S->0A|1D|$\n" +
                    "A->1B|$\n" +
                    "B->1D|0A|$\n" +
                    "D->0C|1B\n" +
                    "C->0A|1D");            //DAHA SONRA BURASI DÜZENLENECEK!!!!
    }//GEN-LAST:event_yardim_butonActionPerformed

    private void hakkimizda_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hakkimizda_butonActionPerformed
        Hakkimizda hakkimizda = new Hakkimizda();
        hakkimizda.setVisible(true);
    }//GEN-LAST:event_hakkimizda_butonActionPerformed

    private void ornekBir_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ornekBir_butonActionPerformed
        String ornekbir = "S->0A|1D|$\n" +
                            "A->1B|$\n" +
                            "B->1D|0A|$\n" +
                            "D->0C|1B\n" +
                            "C->0A|1D";
        
        yazi_alani.setText(ornekbir);
    }//GEN-LAST:event_ornekBir_butonActionPerformed

    private void ornekiki_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ornekiki_butonActionPerformed
        String ornekiki = "A->1B|$C|$\n" +
                          "B->0B|0C|1C\n" +
                          "C->0A ";
        
        yazi_alani.setText(ornekiki);
    }//GEN-LAST:event_ornekiki_butonActionPerformed

    private void ornekUc_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ornekUc_butonActionPerformed
        String ornekuc = "A->0A|1A|0B\n" +
                         "B->1C\n" +
                         "C->$";
        
        yazi_alani.setText(ornekuc);
    }//GEN-LAST:event_ornekUc_butonActionPerformed

    private void yaziRengi_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaziRengi_butonActionPerformed
        Color color = JColorChooser.showDialog(this, "Bir renk seçiniz.", Color.BLACK);
        yazi_alani.setForeground(color);
    }//GEN-LAST:event_yaziRengi_butonActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void yaziTipi_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaziTipi_butonActionPerformed
        YaziTipi yazitipiframe = new YaziTipi();
        yazitipiframe.setVisible(true);
    }//GEN-LAST:event_yaziTipi_butonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtomataMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtomataMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtomataMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtomataMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OtomataMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Mdosya_buton;
    private javax.swing.JMenuItem cikis_buton;
    private javax.swing.JLabel cizimin_yapilacagi_alan;
    private javax.swing.JButton dfa_olustur_buton;
    private javax.swing.JMenuItem dosyaAc_buton;
    private javax.swing.JMenuItem dosyaKaydet_buton;
    private javax.swing.JMenuItem hakkimizda_buton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nfa_olustur_buton;
    private javax.swing.JMenuItem ornekBir_buton;
    private javax.swing.JMenuItem ornekUc_buton;
    private javax.swing.JMenuItem ornekiki_buton;
    private javax.swing.JMenuItem yardim_buton;
    private javax.swing.JMenuItem yaziRengi_buton;
    private javax.swing.JMenuItem yaziTipi_buton;
    public javax.swing.JTextArea yazi_alani;
    // End of variables declaration//GEN-END:variables
}
