/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otomataproje;

/**
 *
 * @author MONSTER
 */
public class OtomataMain extends javax.swing.JFrame {

    /**
     * Creates new form OtomataMain
     */
    public OtomataMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cizimin_yapilacagi_alan = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Mdosya_buton = new javax.swing.JMenu();
        dosyaAc_buton = new javax.swing.JMenuItem();
        dosyaKaydet_buton = new javax.swing.JMenuItem();
        cikis_buton = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        yardim_buton = new javax.swing.JMenuItem();
        hakkimizda_buton = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        ornekBir_buton = new javax.swing.JMenuItem();
        ornekiki_buton = new javax.swing.JMenuItem();
        ornekUc_buton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Otomata Projesi");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("NFA OLUŞTUR");

        jButton2.setText("DFA OLUŞTUR");

        cizimin_yapilacagi_alan.setText("ÇİZİM YAPILACAK ALAN");

        Mdosya_buton.setText("Dosya");

        dosyaAc_buton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        dosyaAc_buton.setText("Dosya Aç");
        Mdosya_buton.add(dosyaAc_buton);

        dosyaKaydet_buton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        dosyaKaydet_buton.setText("Dosya Kaydet");
        Mdosya_buton.add(dosyaKaydet_buton);

        cikis_buton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        cikis_buton.setText("Çıkış");
        Mdosya_buton.add(cikis_buton);

        jMenuBar1.add(Mdosya_buton);

        jMenu4.setText("Yardım");

        yardim_buton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        yardim_buton.setText("Yardım");
        jMenu4.add(yardim_buton);

        hakkimizda_buton.setText("Hakkımızda");
        jMenu4.add(hakkimizda_buton);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Örnekler");

        ornekBir_buton.setText("Örnek 1");
        jMenu5.add(ornekBir_buton);

        ornekiki_buton.setText("Örnek 2");
        jMenu5.add(ornekiki_buton);

        ornekUc_buton.setText("Örnek 3");
        jMenu5.add(ornekUc_buton);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cizimin_yapilacagi_alan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 892, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(cizimin_yapilacagi_alan, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtomataMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtomataMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtomataMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtomataMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OtomataMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Mdosya_buton;
    private javax.swing.JMenuItem cikis_buton;
    private javax.swing.JLabel cizimin_yapilacagi_alan;
    private javax.swing.JMenuItem dosyaAc_buton;
    private javax.swing.JMenuItem dosyaKaydet_buton;
    private javax.swing.JMenuItem hakkimizda_buton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuItem ornekBir_buton;
    private javax.swing.JMenuItem ornekUc_buton;
    private javax.swing.JMenuItem ornekiki_buton;
    private javax.swing.JMenuItem yardim_buton;
    // End of variables declaration//GEN-END:variables
}
