//YAZI TİPLERİ AKTARILMAMAKTADIR. SORUNU BUL VE ÇÖZ (EN KISA YNTEM OTOMATAMAİN FRAMESİNİN İÇİNE EK FRAME EKLEMEK). 197.VIDEO 5.DAKIKA!!!!
package otomataproje;

import java.awt.Font;


public class YaziTipi extends javax.swing.JFrame {

    /**
     * Creates new form YaziTipi
     */
    public YaziTipi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        newtimesroman_buton = new javax.swing.JRadioButton();
        calibri_buton = new javax.swing.JRadioButton();
        arial_buton = new javax.swing.JRadioButton();
        couriernew_buton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yazı Tipi");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Lütfen aşağıdan bir yazı tipi seçiniz.");

        buttonGroup2.add(newtimesroman_buton);
        newtimesroman_buton.setText("Times New Roman");
        newtimesroman_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newtimesroman_butonActionPerformed(evt);
            }
        });

        buttonGroup2.add(calibri_buton);
        calibri_buton.setText("Calibri");
        calibri_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calibri_butonActionPerformed(evt);
            }
        });

        buttonGroup2.add(arial_buton);
        arial_buton.setText("Arial");
        arial_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arial_butonActionPerformed(evt);
            }
        });

        buttonGroup2.add(couriernew_buton);
        couriernew_buton.setText("Courier New");
        couriernew_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                couriernew_butonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("Tamam");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(couriernew_buton)
                            .addComponent(arial_buton)
                            .addComponent(calibri_buton)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newtimesroman_buton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newtimesroman_buton)
                .addGap(18, 18, 18)
                .addComponent(calibri_buton)
                .addGap(18, 18, 18)
                .addComponent(arial_buton)
                .addGap(18, 18, 18)
                .addComponent(couriernew_buton)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newtimesroman_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newtimesroman_butonActionPerformed
        
        Font font = new Font("Times New Roman", Font.PLAIN, 20);    
        OtomataMain mainclass = new OtomataMain();       
        mainclass.yazi_alani.setFont(font);
    }//GEN-LAST:event_newtimesroman_butonActionPerformed

    private void calibri_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calibri_butonActionPerformed
        Font font = new Font("Calibri", Font.PLAIN, 20);    
        OtomataMain mainclass = new OtomataMain();       
        mainclass.yazi_alani.setFont(font);
    }//GEN-LAST:event_calibri_butonActionPerformed

    private void arial_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arial_butonActionPerformed
        Font font = new Font("Arial", Font.PLAIN, 20);    
        OtomataMain mainclass = new OtomataMain();       
        mainclass.yazi_alani.setFont(font);
    }//GEN-LAST:event_arial_butonActionPerformed

    private void couriernew_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_couriernew_butonActionPerformed
        Font font = new Font("Courier New", Font.PLAIN, 20);    
        OtomataMain mainclass = new OtomataMain();       
        mainclass.yazi_alani.setFont(font);
    }//GEN-LAST:event_couriernew_butonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(arial_buton.isSelected()){
            Font font = new Font("Arial", Font.PLAIN, 20);    
            OtomataMain mainclass = new OtomataMain();       
            mainclass.yazi_alani.setFont(font); 
        }else if(newtimesroman_buton.isSelected()){
            Font font = new Font("Times New Roman", Font.PLAIN, 20);    
            OtomataMain mainclass = new OtomataMain();       
            mainclass.yazi_alani.setFont(font);
        }else if(calibri_buton.isSelected()){
            Font font = new Font("Calibri", Font.PLAIN, 20);    
            OtomataMain mainclass = new OtomataMain();       
            mainclass.yazi_alani.setFont(font);
        }else{
            Font font = new Font("Courier New", Font.PLAIN, 20);    
            OtomataMain mainclass = new OtomataMain();       
            mainclass.yazi_alani.setFont(font);
        }
                
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YaziTipi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YaziTipi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YaziTipi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YaziTipi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YaziTipi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton arial_buton;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton calibri_buton;
    private javax.swing.JRadioButton couriernew_buton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton newtimesroman_buton;
    // End of variables declaration//GEN-END:variables
}
